#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../include/beamer_generator.h"

/*
 * Statistics used by the presentation.
 *
 * These values are calculated directly from the token array
 * produced by the scanner.
 */
typedef struct {
    size_t keyword_count;
    size_t identifier_count;
    size_t constant_count;
    size_t string_literal_count;
    size_t operator_count;
    size_t punctuator_count;
    size_t error_count;
    size_t total_tokens;
} BeamerStats;


/*
 * Calculates lexical-category statistics from the tokens
 * generated by the scanner.
 */
static void calculate_stats(
    const Token *tokens,
    size_t token_count,
    BeamerStats *stats
) {
    memset(stats, 0, sizeof(BeamerStats));

    for (size_t i = 0; i < token_count; i++) {

        switch (tokens[i].category) {

            case CAT_KEYWORD:
                stats->keyword_count++;
                break;

            case CAT_IDENTIFIER:
                stats->identifier_count++;
                break;

            case CAT_CONSTANT:
                stats->constant_count++;
                break;

            case CAT_STRING_LITERAL:
                stats->string_literal_count++;
                break;

            case CAT_OPERATOR:
                stats->operator_count++;
                break;

            case CAT_PUNCTUATOR:
                stats->punctuator_count++;
                break;

            case CAT_ERROR:
                stats->error_count++;
                break;

            case CAT_EOF:
                continue;
        }

        stats->total_tokens++;
    }
}


/*
 * Prints text safely inside LaTeX.
 *
 * Some characters have a special meaning in LaTeX and must
 * therefore be escaped before being written to the .tex file.
 */
static void write_latex_escaped(
    FILE *file,
    const char *text
) {
    if (text == NULL) {
        return;
    }

    while (*text != '\0') {

        switch (*text) {

            case '\\':
                fprintf(file, "\\textbackslash{}");
                break;

            case '{':
                fprintf(file, "\\{");
                break;

            case '}':
                fprintf(file, "\\}");
                break;

            case '$':
                fprintf(file, "\\$");
                break;

            case '&':
                fprintf(file, "\\&");
                break;

            case '#':
                fprintf(file, "\\#");
                break;

            case '_':
                fprintf(file, "\\_");
                break;

            case '%':
                fprintf(file, "\\%%");
                break;

            case '^':
                fprintf(file, "\\textasciicircum{}");
                break;

            case '~':
                fprintf(file, "\\textasciitilde{}");
                break;

            default:
                fputc(*text, file);
                break;
        }

        text++;
    }
}


/*
 * Writes the LaTeX preamble.
 *
 * This part is static and is included in every presentation.
 */
static void write_preamble(FILE *file) {

    fprintf(file,
        "\\documentclass[aspectratio=169]{beamer}\n"
        "\n"
        "\\usetheme{Madrid}\n"
        "\\usecolortheme{default}\n"
        "\\usefonttheme{serif}\n"
        "\n"
        "\\usepackage{lmodern}\n"
        "\\usepackage[utf8]{inputenc}\n"
        "\\usepackage[T1]{fontenc}\n"
        "\\usepackage[english]{babel}\n"
        "\\usepackage{listings}\n"
        "\\usepackage{xcolor}\n"
        "\\usepackage{tikz}\n"
        "\\usepackage{pgfplots}\n"
        "\n"
        "\\pgfplotsset{compat=1.18}\n"
        "\\usepgfplotslibrary{polar}\n"
        "\n"
        "\\definecolor{keywordcolor}{RGB}{30,90,180}\n"
        "\\definecolor{identifiercolor}{RGB}{30,30,30}\n"
        "\\definecolor{constantcolor}{RGB}{150,40,150}\n"
        "\\definecolor{stringcolor}{RGB}{20,130,70}\n"
        "\\definecolor{operatorcolor}{RGB}{210,100,20}\n"
        "\\definecolor{punctuatorcolor}{RGB}{90,90,90}\n"
        "\\definecolor{errorcolor}{RGB}{190,30,30}\n"
        "\n"
        "\\lstdefinestyle{cstyle}{\n"
        "    language=C,\n"
        "    basicstyle=\\ttfamily\\small,\n"
        "    keywordstyle=\\color{keywordcolor}\\bfseries,\n"
        "    stringstyle=\\color{stringcolor},\n"
        "    commentstyle=\\color{gray}\\itshape,\n"
        "    numbers=left,\n"
        "    numberstyle=\\tiny\\color{gray},\n"
        "    numbersep=8pt,\n"
        "    frame=single,\n"
        "    breaklines=true,\n"
        "    showstringspaces=false,\n"
        "    tabsize=4\n"
        "}\n"
        "\n"
    );
}


/*
 * Writes the presentation cover.
 */
static void write_title_slide(FILE *file) {

     fprintf(file,
        "\\begin{frame}{Project 1}\n"
        "\n"
        "\\centering\n"
        "\n"
        "{\\Large\\textsc{University of Costa Rica}}\\\\[0.15cm]\n"
        "{\\large School of Computer Science and Informatics}\\\\[0.10cm]\n"
        "{\\normalsize CI-0146 Compilers}\\\\[0.35cm]\n"
        "\n"
        "\\rule{0.78\\textwidth}{0.5pt}\\\\[0.22cm]\n"
        "\n"
        "{\\Large\\bfseries Lexical Analyzer}\\\\[0.14cm]\n"
        "{\\normalsize Scanner for the C Programming Language}\\\\[0.22cm]\n"
        "\n"
        "\\rule{0.78\\textwidth}{0.5pt}\\\\[0.38cm]\n"
        "\n"
        "\\begin{columns}[T,onlytextwidth]\n"
        "\n"
        "\\begin{column}{0.46\\textwidth}\n"
        "\\raggedright\n"
        "{\\large\\textbf{Professor:}}\\\\[0.08cm]\n"
        "{\\normalsize Dr. Francisco J. Torres-Rojas}\n"
        "\\end{column}\n"
        "\n"
        "\\begin{column}{0.50\\textwidth}\n"
        "\\raggedleft\n"
        "{\\large\\textbf{Students:}}\\\\[0.08cm]\n"
        "{\\normalsize José Guerra --- C33510}\\\\\n"
        "{\\normalsize Mario Cordero --- C22306}\\\\\n"
        "{\\normalsize Daniel Gómez --- C23310}\n"
        "\\end{column}\n"
        "\n"
        "\\end{columns}\n"
        "\n"
        "\\vfill\n"
        "{\\small II Semester 2026}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes the general process followed by the project.
 */
static void write_process_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{General Process}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}[\n"
        "    node distance=1.4cm,\n"
        "    box/.style={\n"
        "        draw,\n"
        "        rounded corners,\n"
        "        minimum width=3.4cm,\n"
        "        minimum height=0.8cm,\n"
        "        align=center\n"
        "    }\n"
        "]\n"
        "\n"
        "\\node[box] (source) {C source file};\n"
        "\\node[box, below of=source] "
        "(preprocessor) {Preprocessor};\n"
        "\\node[box, below of=preprocessor] "
        "(temporary) {Temporary file};\n"
        "\\node[box, below of=temporary] "
        "(scanner) {Lexical scanner};\n"
        "\\node[box, below of=scanner] "
        "(tokens) {Tokens and statistics};\n"
        "\n"
        "\\draw[->, thick] (source) -- (preprocessor);\n"
        "\\draw[->, thick] (preprocessor) -- (temporary);\n"
        "\\draw[->, thick] (temporary) -- (scanner);\n"
        "\\draw[->, thick] (scanner) -- (tokens);\n"
        "\n"
        "\\end{tikzpicture}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes a general explanation of Flex.
 */
static void write_flex_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{Using Flex}\n"
        "\n"
        "\\begin{itemize}\n"
        "    \\item Flex allows patterns to be defined using "
        "regular expressions.\n"
        "\n"
        "    \\item Each pattern is associated with an action "
        "written in C.\n"
        "\n"
        "    \\item From a \\texttt{.l} file, Flex generates "
        "C source code.\n"
        "\n"
        "    \\item The scanner processes the input and recognizes "
        "the different lexemes.\n"
        "\n"
        "    \\item Each lexeme is classified into "
        "a lexical category.\n"
        "\\end{itemize}\n"
        "\n"
        "\\vspace{0.4cm}\n"
        "\n"
        "\\begin{block}{Basic Flow}\n"
        "\\texttt{scanner.l}\n"
        "$\\rightarrow$\n"
        "\\texttt{Flex}\n"
        "$\\rightarrow$\n"
        "\\texttt{scanner.lex.c}\n"
        "$\\rightarrow$\n"
        "\\texttt{executable}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes information about the original source file and the
 * temporary preprocessed file used as input for the scanner.
 */
static void write_input_slide(
    FILE *file,
    const char *source_filename,
    const char *preprocessed_filename
) {

    fprintf(file,
        "\\begin{frame}{Processed Files}\n"
        "\n"
        "\\begin{block}{Source file}\n"
        "\\texttt{"
    );

    write_latex_escaped(file, source_filename);

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "\\begin{block}{File after preprocessing}\n"
        "\\texttt{"
    );

    write_latex_escaped(file, preprocessed_filename);

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "The scanner uses the temporary file generated by "
        "the preprocessor as its actual input.\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes a summary table containing the lexical categories
 * found by the scanner.
 */
static void write_statistics_slide(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Lexical Analysis Summary}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tabular}{lr}\n"
        "\\textbf{Category} & "
        "\\textbf{Count} \\\\ \\hline\n"
        "\n"
        "Keywords & %zu \\\\\n"
        "Identifiers & %zu \\\\\n"
        "Constants & %zu \\\\\n"
        "String literals & %zu \\\\\n"
        "Operators & %zu \\\\\n"
        "Punctuators & %zu \\\\\n"
        "Lexical errors & %zu \\\\\n"
        "\\hline\n"
        "\\textbf{Total} & \\textbf{%zu} \\\\\n"
        "\\end{tabular}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count,
        stats->total_tokens
    );
}


/*
 * Writes a histogram containing the number of tokens
 * in each lexical category.
 */
static void write_histogram(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Histogram of Lexical Categories}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}\n"
        "\n"
        "\\begin{axis}[\n"
        "    ybar,\n"
        "    width=11.5cm,\n"
        "    height=6cm,\n"
        "    ylabel={Count},\n"
        "    symbolic x coords={"
        "Keyword,Identifier,Constant,String,"
        "Operator,Punctuator,Error},\n"
        "    xtick=data,\n"
        "    x tick label style={\n"
        "        rotate=35,\n"
        "        anchor=east,\n"
        "        font=\\scriptsize\n"
        "    },\n"
        "    ymin=0,\n"
        "    nodes near coords,\n"
        "    enlargelimits=0.15\n"
        "]\n"
        "\n"
        "\\addplot coordinates {\n"
        "    (Keyword,%zu)\n"
        "    (Identifier,%zu)\n"
        "    (Constant,%zu)\n"
        "    (String,%zu)\n"
        "    (Operator,%zu)\n"
        "    (Punctuator,%zu)\n"
        "    (Error,%zu)\n"
        "};\n"
        "\n"
        "\\end{axis}\n"
        "\n"
        "\\end{tikzpicture}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count
    );
}


/*
 * Writes the lexical-error slide.
 */
static void write_error_slide(
    FILE *file,
    const Token *tokens,
    size_t token_count
) {
    size_t error_count = 0;

    for (size_t i = 0; i < token_count; i++) {

        if (tokens[i].category == CAT_ERROR) {
            error_count++;
        }
    }

    fprintf(file,
        "\\begin{frame}{Lexical Errors}\n"
        "\n"
    );

    if (error_count == 0) {

        fprintf(file,
            "\\begin{block}{Result}\n"
            "No lexical errors were found.\n"
            "\\end{block}\n"
        );

    } else {

        fprintf(file,
            "%zu lexical errors were found.\n"
            "\n"
            "\\vspace{0.3cm}\n"
            "\n"
            "\\begin{tabular}{lll}\n"
            "\\textbf{Lexeme} & "
            "\\textbf{Line} & "
            "\\textbf{Column} \\\\ \\hline\n",
            error_count
        );

        for (size_t i = 0; i < token_count; i++) {

            if (tokens[i].category != CAT_ERROR) {
                continue;
            }

            fprintf(file, "\\texttt{");

            write_latex_escaped(
                file,
                tokens[i].lexeme
            );

            fprintf(file,
                "} & %d & %d \\\\\n",
                tokens[i].line,
                tokens[i].column
            );
        }

        fprintf(file,
            "\\end{tabular}\n"
        );
    }

    fprintf(file,
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes one sector of the dynamic pie chart.
 */
static void write_pie_sector(
    FILE *file,
    double start_angle,
    double end_angle,
    const char *color
) {
    if (end_angle <= start_angle) {
        return;
    }

    fprintf(file,
        "\\path[\n"
        "    fill=%s,\n"
        "    draw=white,\n"
        "    thick\n"
        "]\n"
        "(axis cs:%.4f,0) --\n"
        "(axis cs:%.4f,1)\n"
        "plot[\n"
        "    domain=%.4f:%.4f,\n"
        "    samples=30\n"
        "] (axis cs:\\x,1)\n"
        "-- (axis cs:%.4f,0)\n"
        "-- cycle;\n"
        "\n",

        color,
        start_angle,
        start_angle,
        start_angle,
        end_angle,
        end_angle
    );
}


/*
 * Writes a dynamic pie chart based on lexical categories.
 */
static void write_pie_chart(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Distribution of Lexical Categories}\n"
        "\n"
    );

    if (stats->total_tokens == 0) {

        fprintf(file,
            "\\centering\n"
            "\n"
            "No tokens were found to display.\n"
            "\n"
            "\\end{frame}\n"
            "\n"
        );

        return;
    }

    double angle = 0.0;

    double keyword_angle =
        360.0 *
        (double) stats->keyword_count /
        (double) stats->total_tokens;

    double identifier_angle =
        360.0 *
        (double) stats->identifier_count /
        (double) stats->total_tokens;

    double constant_angle =
        360.0 *
        (double) stats->constant_count /
        (double) stats->total_tokens;

    double string_angle =
        360.0 *
        (double) stats->string_literal_count /
        (double) stats->total_tokens;

    double operator_angle =
        360.0 *
        (double) stats->operator_count /
        (double) stats->total_tokens;

    double punctuator_angle =
        360.0 *
        (double) stats->punctuator_count /
        (double) stats->total_tokens;

    double error_angle =
        360.0 *
        (double) stats->error_count /
        (double) stats->total_tokens;

    fprintf(file,
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}\n"
        "\n"
        "\\begin{polaraxis}[\n"
        "    hide axis,\n"
        "    xmin=0,\n"
        "    xmax=360,\n"
        "    ymin=0,\n"
        "    ymax=1,\n"
        "    width=7cm,\n"
        "    height=7cm\n"
        "]\n"
        "\n"
    );

    write_pie_sector(
        file,
        angle,
        angle + keyword_angle,
        "blue!65"
    );
    angle += keyword_angle;

    write_pie_sector(
        file,
        angle,
        angle + identifier_angle,
        "green!60"
    );
    angle += identifier_angle;

    write_pie_sector(
        file,
        angle,
        angle + constant_angle,
        "orange!70"
    );
    angle += constant_angle;

    write_pie_sector(
        file,
        angle,
        angle + string_angle,
        "cyan!60"
    );
    angle += string_angle;

    write_pie_sector(
        file,
        angle,
        angle + operator_angle,
        "violet!60"
    );
    angle += operator_angle;

    write_pie_sector(
        file,
        angle,
        angle + punctuator_angle,
        "yellow!70"
    );
    angle += punctuator_angle;

    write_pie_sector(
        file,
        angle,
        angle + error_angle,
        "red!65"
    );

    fprintf(file,
        "\\end{polaraxis}\n"
        "\n"
        "\\end{tikzpicture}\n"
        "\n"
        "\\scriptsize\n"
        "\n"
        "\\begin{tabular}{lll}\n"
        "\\textcolor{blue!65}{\\rule{0.25cm}{0.25cm}} "
        "Keywords: %zu &\n"
        "\\textcolor{green!60}{\\rule{0.25cm}{0.25cm}} "
        "Identifiers: %zu &\n"
        "\\textcolor{orange!70}{\\rule{0.25cm}{0.25cm}} "
        "Constants: %zu \\\\[0.15cm]\n"
        "\n"
        "\\textcolor{cyan!60}{\\rule{0.25cm}{0.25cm}} "
        "Strings: %zu &\n"
        "\\textcolor{violet!60}{\\rule{0.25cm}{0.25cm}} "
        "Operators: %zu &\n"
        "\\textcolor{yellow!70}{\\rule{0.25cm}{0.25cm}} "
        "Punctuators: %zu \\\\[0.15cm]\n"
        "\n"
        "\\textcolor{red!65}{\\rule{0.25cm}{0.25cm}} "
        "Errors: %zu & &\n"
        "\\end{tabular}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count
    );
}


/*
 * Writes the final presentation slide.
 */
static void write_end_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{End}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\vfill\n"
        "\n"
        "{\\Huge\\bfseries Thank You}\\\\[0.45cm]\n"
        "{\\Large Project 1 --- Lexical Analyzer}\\\\[0.20cm]\n"
        "{\\large Scanner for the C Programming Language}\n"
        "\n"
        "\\vfill\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Generates the complete Beamer .tex file.
 */
int beamer_generate(
    const char *output_filename,
    const char *source_filename,
    const char *preprocessed_filename,
    const Token *tokens,
    size_t token_count
) {

    if (output_filename == NULL ||
        source_filename == NULL ||
        preprocessed_filename == NULL) {

        return 0;
    }

    if (tokens == NULL && token_count > 0) {
        return 0;
    }

    FILE *file = fopen(output_filename, "w");

    if (file == NULL) {

        fprintf(
            stderr,
            "Error: no se pudo crear %s\n",
            output_filename
        );

        return 0;
    }

    BeamerStats stats;

    calculate_stats(
        tokens,
        token_count,
        &stats
    );

    write_preamble(file);

    fprintf(file, "\\begin{document}\n\n");

    write_title_slide(file);

    write_process_slide(file);

    write_flex_slide(file);

    write_input_slide(
        file,
        source_filename,
        preprocessed_filename
    );

    write_statistics_slide(
        file,
        &stats
    );

    write_histogram(
        file,
        &stats
    );

    write_pie_chart(
        file,
        &stats
    );

    write_error_slide(
        file,
        tokens,
        token_count
    );

    /*
     * Pending:
     *
     * Generate slides containing the preprocessed source
     * with every lexeme colored according to the category
     * returned by the scanner.
     */

    write_end_slide(file);

    fprintf(file, "\\end{document}\n");

    fclose(file);

    return 1;
}