#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>

#include "../include/beamer_generator.h"

#define SOURCE_LINES_PER_SLIDE 12

/*
 * Statistics used by the presentation.
 *
 * These values are calculated directly from the token array
 * produced by the scanner.
 */
typedef struct {
    size_t keyword_count;
    size_t identifier_count;
    size_t constant_count;
    size_t string_literal_count;
    size_t operator_count;
    size_t punctuator_count;
    size_t error_count;
    size_t total_tokens;
} BeamerStats;

static void write_code_legend(
    FILE *file
);

static int write_source_slides(
    FILE *file,
    const char *preprocessed_filename,
    const Token *tokens,
    size_t token_count
);

/*
 * Calculates lexical-category statistics from the tokens
 * generated by the scanner.
 */
static void calculate_stats(
    const Token *tokens,
    size_t token_count,
    BeamerStats *stats
) {
    memset(stats, 0, sizeof(BeamerStats));

    for (size_t i = 0; i < token_count; i++) {

        switch (tokens[i].category) {

            case CAT_KEYWORD:
                stats->keyword_count++;
                break;

            case CAT_IDENTIFIER:
                stats->identifier_count++;
                break;

            case CAT_CONSTANT:
                stats->constant_count++;
                break;

            case CAT_STRING_LITERAL:
                stats->string_literal_count++;
                break;

            case CAT_OPERATOR:
                stats->operator_count++;
                break;

            case CAT_PUNCTUATOR:
                stats->punctuator_count++;
                break;

            case CAT_ERROR:
                stats->error_count++;
                break;

            case CAT_EOF:
                continue;
        }

        stats->total_tokens++;
    }
}


/*
 * Prints text safely inside LaTeX.
 *
 * Some characters have a special meaning in LaTeX and must
 * therefore be escaped before being written to the .tex file.
 */
static void write_latex_escaped(
    FILE *file,
    const char *text
) {
    if (text == NULL) {
        return;
    }

    while (*text != '\0') {

        switch (*text) {

            case '\\':
                fprintf(file, "\\textbackslash{}");
                break;

            case '{':
                fprintf(file, "\\{");
                break;

            case '}':
                fprintf(file, "\\}");
                break;

            case '$':
                fprintf(file, "\\$");
                break;

            case '&':
                fprintf(file, "\\&");
                break;

            case '#':
                fprintf(file, "\\#");
                break;

            case '_':
                fprintf(file, "\\_");
                break;

            case '%':
                fprintf(file, "\\%%");
                break;

            case '^':
                fprintf(file, "\\textasciicircum{}");
                break;

            case '~':
                fprintf(file, "\\textasciitilde{}");
                break;

            default:
                fputc(*text, file);
                break;
        }

        text++;
    }
}

static void write_code_escaped(
    FILE *file,
    const char *text
) {
    if (file == NULL || text == NULL) {
        return;
    }

    for (const char *p = text; *p != '\0'; p++) {

        switch (*p) {

            case '\\':
                fprintf(file, "\\textbackslash{}");
                break;

            case '{':
                fprintf(file, "\\{");
                break;

            case '}':
                fprintf(file, "\\}");
                break;

            case '$':
                fprintf(file, "\\$");
                break;

            case '&':
                fprintf(file, "\\&");
                break;

            case '#':
                fprintf(file, "\\#");
                break;

            case '_':
                fprintf(file, "\\_");
                break;

            case '%':
                fprintf(file, "\\%%");
                break;

            case '^':
                fprintf(file, "\\textasciicircum{}");
                break;

            case '~':
                fprintf(file, "\\textasciitilde{}");
                break;

            /*
             * Avoid LaTeX converting -- into
             * a typographical dash.
             */
            case '-':
                fprintf(file, "\\char45{}");
                break;

            default:
                fputc(*p, file);
                break;
        }
    }
}

static const char *category_color(
    TokenCategory category
) {
    switch (category) {

        case CAT_KEYWORD:
            return "keywordcolor";

        case CAT_IDENTIFIER:
            return "identifiercolor";

        case CAT_CONSTANT:
            return "constantcolor";

        case CAT_STRING_LITERAL:
            return "stringcolor";

        case CAT_OPERATOR:
            return "operatorcolor";

        case CAT_PUNCTUATOR:
            return "punctuatorcolor";

        case CAT_ERROR:
            return "errorcolor";

        case CAT_EOF:
            return "black";
    }

    return "black";
}

static void write_styled_token(
    FILE *file,
    const Token *token
) {
    if (file == NULL ||
        token == NULL ||
        token->lexeme == NULL) {

        return;
    }

    const char *command = NULL;

    switch (token->category) {

        case CAT_KEYWORD:
            command = "tokkeyword";
            break;

        case CAT_IDENTIFIER:
            command = "tokidentifier";
            break;

        case CAT_CONSTANT:
            command = "tokconstant";
            break;

        case CAT_STRING_LITERAL:
            command = "tokstring";
            break;

        case CAT_OPERATOR:
            command = "tokoperator";
            break;

        case CAT_PUNCTUATOR:
            command = "tokpunctuator";
            break;

        case CAT_ERROR:
            command = "tokerror";
            break;

        case CAT_EOF:
            return;
    }

    fprintf(
        file,
        "(*@\\%s{",
        command
    );

    write_code_escaped(
        file,
        token->lexeme
    );

    fprintf(
        file,
        "}@*)"
    );
}

static size_t count_source_lines(
    FILE *input
) {
    if (input == NULL) {
        return 0;
    }

    size_t lines = 0;

    int character;
    int last_character = '\n';
    int has_content = 0;

    rewind(input);

    while ((character = fgetc(input)) != EOF) {

        has_content = 1;

        if (character == '\n') {
            lines++;
        }

        last_character = character;
    }

    /*
     * Count the last line if the file does not end
     * with a newline.
     */
    if (has_content &&
        last_character != '\n') {

        lines++;
    }

    rewind(input);

    return lines;
}

static void write_source_line(
    FILE *file,
    const char *line,
    size_t line_number,
    const Token *tokens,
    size_t token_count,
    size_t *token_index
) {
    if (file == NULL ||
        line == NULL ||
        tokens == NULL ||
        token_index == NULL) {

        return;
    }

    size_t line_length = strlen(line);

    /*
     * getline() includes the newline character.
     * listings will receive the newline separately.
     */
    while (line_length > 0 &&
           (line[line_length - 1] == '\n' ||
            line[line_length - 1] == '\r')) {

        line_length--;
    }

    size_t cursor = 0;

    /*
     * Normally this should not be necessary because
     * tokens are ordered, but it keeps the function
     * defensive.
     */
    while (*token_index < token_count &&
           tokens[*token_index].line <
               (int) line_number) {

        (*token_index)++;
    }

    while (*token_index < token_count &&
           tokens[*token_index].line ==
               (int) line_number) {

        const Token *token =
            &tokens[*token_index];

        if (token->lexeme == NULL) {

            (*token_index)++;
            continue;
        }

        /*
         * Scanner columns are assumed to start at 1.
         */
        size_t token_start = 0;

        if (token->column > 0) {
            token_start =
                (size_t) token->column - 1;
        }

        /*
         * Prevent invalid positions from reading beyond
         * the current source line.
         */
        if (token_start > line_length) {
            token_start = line_length;
        }

        /*
         * Write all untouched characters before the token.
         * These are normally spaces or tabs.
         */
        if (token_start > cursor) {

            fwrite(
                line + cursor,
                sizeof(char),
                token_start - cursor,
                file
            );
        }

        /*
         * Replace the original lexeme with the styled
         * representation of the token.
         */
        write_styled_token(
            file,
            token
        );

        size_t token_length =
            strlen(token->lexeme);

        size_t token_end =
            token_start + token_length;

        if (token_end > line_length) {
            token_end = line_length;
        }

        cursor = token_end;

        (*token_index)++;
    }

    /*
     * Write any remaining text after the last token.
     */
    if (cursor < line_length) {

        fwrite(
            line + cursor,
            sizeof(char),
            line_length - cursor,
            file
        );
    }

    fputc('\n', file);
}

static int write_source_slides(
    FILE *file,
    const char *preprocessed_filename,
    const Token *tokens,
    size_t token_count
) {
    if (file == NULL ||
        preprocessed_filename == NULL ||
        tokens == NULL) {

        return 0;
    }

    FILE *input =
        fopen(
            preprocessed_filename,
            "r"
        );

    if (input == NULL) {

        fprintf(
            stderr,
            "Error: could not open "
            "preprocessed source file: %s\n",
            preprocessed_filename
        );

        return 0;
    }

    size_t total_lines =
        count_source_lines(input);

    /*
     * Empty source file.
     */
    if (total_lines == 0) {

        fprintf(
            file,
            "\\begin{frame}"
            "{Preprocessed Source Code}\n"
            "\\centering\n"
            "\\vfill\n"
            "The preprocessed source file is empty.\n"
            "\\vfill\n"
            "\\end{frame}\n\n"
        );

        fclose(input);

        return 1;
    }

    char *line = NULL;
    size_t line_capacity = 0;

    size_t current_line = 1;
    size_t token_index = 0;

    while (current_line <= total_lines) {

        size_t first_line =
            current_line;

        size_t last_line =
            first_line +
            SOURCE_LINES_PER_SLIDE - 1;

        if (last_line > total_lines) {
            last_line = total_lines;
        }

        /*
         * lstlisting requires a fragile Beamer frame.
         */
        fprintf(
            file,
            "\\begin{frame}[fragile]"
            "{Preprocessed Source Code -- "
            "Lines %zu--%zu}\n"
            "\\vspace{-0.15cm}\n"
            "\n",
            first_line,
            last_line
        );

        fprintf(
            file,
            "\\begin{lstlisting}["
            "style=sourcecode,"
            "firstnumber=%zu]\n",
            first_line
        );

        while (current_line <= last_line) {

            ssize_t read =
                getline(
                    &line,
                    &line_capacity,
                    input
                );

            if (read == -1) {
                break;
            }

            write_source_line(
                file,
                line,
                current_line,
                tokens,
                token_count,
                &token_index
            );

            current_line++;
        }

        fprintf(
            file,
            "\\end{lstlisting}\n"
        );

        /*
         * Keep the legend visible on every code slide.
         */
        write_code_legend(file);

        fprintf(
            file,
            "\\end{frame}\n"
            "\n"
        );
    }

    free(line);

    fclose(input);

    return 1;
}

/*
 * Writes the LaTeX preamble.
 *
 * This part is static and is included in every presentation.
 */
static void write_preamble(FILE *file) {

    fprintf(file,
        "\\documentclass[aspectratio=169]{beamer}\n"
        "\n"
        "\\usetheme{Madrid}\n"
        "\\usecolortheme{default}\n"
        "\\usefonttheme{serif}\n"
        "\n"
        "\\usepackage{lmodern}\n"
        "\\usepackage[utf8]{inputenc}\n"
        "\\usepackage[T1]{fontenc}\n"
        "\\usepackage[english]{babel}\n"
        "\\usepackage{listings}\n"
        "\\usepackage{xcolor}\n"
        "\\usepackage{tikz}\n"
        "\\usepackage{pgfplots}\n"
        "\n"
        "\\pgfplotsset{compat=1.18}\n"
        "\\usepgfplotslibrary{polar}\n"
        "\n"
        "\\definecolor{keywordcolor}{RGB}{30,90,180}\n"
        "\\definecolor{identifiercolor}{RGB}{35,35,35}\n"
        "\\definecolor{constantcolor}{RGB}{150,40,150}\n"
        "\\definecolor{stringcolor}{RGB}{20,130,70}\n"
        "\\definecolor{operatorcolor}{RGB}{210,100,20}\n"
        "\\definecolor{punctuatorcolor}{RGB}{60,95,130}\n"
        "\\definecolor{errorcolor}{RGB}{190,30,30}\n"
        "\n"
        "\\definecolor{keywordbg}{RGB}{220,230,255}\n"
        "\\definecolor{identifierbg}{RGB}{238,238,238}\n"
        "\\definecolor{constantbg}{RGB}{245,225,245}\n"
        "\\definecolor{stringbg}{RGB}{220,245,230}\n"
        "\\definecolor{operatorbg}{RGB}{255,235,210}\n"
        "\\definecolor{punctuatorbg}{RGB}{225,235,245}\n"
        "\\definecolor{errorbg}{RGB}{255,215,215}\n"
        "\n"
        "\\setlength{\\fboxsep}{1.2pt}\n"
        "\n"

        "\\setlength{\\fboxsep}{1.0pt}\n"
        "\\setlength{\\fboxrule}{0.4pt}\n"
        "\n"

        "\\newcommand{\\tokkeyword}[1]{"
        "\\fcolorbox{keywordcolor}{keywordbg}{"
        "\\textcolor{keywordcolor}{\\texttt{\\textbf{#1}}}}}\n"

        "\\newcommand{\\tokidentifier}[1]{"
        "\\fcolorbox{identifiercolor}{identifierbg}{"
        "\\textcolor{identifiercolor}{\\texttt{#1}}}}\n"

        "\\newcommand{\\tokconstant}[1]{"
        "\\fcolorbox{constantcolor}{constantbg}{"
        "\\textcolor{constantcolor}{\\texttt{\\textbf{#1}}}}}\n"

        "\\newcommand{\\tokstring}[1]{"
        "\\fcolorbox{stringcolor}{stringbg}{"
        "\\textcolor{stringcolor}{\\texttt{\\textit{#1}}}}}\n"

        "\\newcommand{\\tokoperator}[1]{"
        "\\fcolorbox{operatorcolor}{operatorbg}{"
        "\\textcolor{operatorcolor}{\\texttt{\\textbf{#1}}}}}\n"

        "\\newcommand{\\tokpunctuator}[1]{"
        "\\fcolorbox{punctuatorcolor}{punctuatorbg}{"
        "\\textcolor{punctuatorcolor}{\\texttt{#1}}}}\n"

        "\\newcommand{\\tokerror}[1]{"
        "\\fcolorbox{errorcolor}{errorbg}{"
        "\\textcolor{errorcolor}{"
        "\\texttt{\\textbf{\\textit{#1}}}}}}\n"
        "\n"

        "\\lstdefinestyle{sourcecode}{\n"
        "    basicstyle=\\ttfamily\\scriptsize,\n"
        "    numbers=left,\n"
        "    numberstyle=\\scriptsize\\color{gray},\n"
        "    numbersep=6pt,\n"
        "    showstringspaces=false,\n"
        "    keepspaces=true,\n"
        "    columns=fullflexible,\n"
        "    breaklines=true,\n"
        "    breakatwhitespace=false,\n"
        "    tabsize=4,\n"
        "    frame=single,\n"
        "    xleftmargin=2.0em,\n"
        "    framexleftmargin=2.0em,\n"
        "    aboveskip=0.2cm,\n"
        "    belowskip=0.1cm,\n"
        "    escapeinside={(*@}{@*)}\n"
        "}\n"

        "\n"
        "\\lstdefinestyle{cstyle}{\n"
        "    language=C,\n"
        "    basicstyle=\\ttfamily\\small,\n"
        "    keywordstyle=\\color{keywordcolor}\\bfseries,\n"
        "    stringstyle=\\color{stringcolor},\n"
        "    commentstyle=\\color{gray}\\itshape,\n"
        "    numbers=left,\n"
        "    numberstyle=\\tiny\\color{gray},\n"
        "    numbersep=8pt,\n"
        "    frame=single,\n"
        "    breaklines=true,\n"
        "    showstringspaces=false,\n"
        "    tabsize=4\n"
        "}\n"
        "\n"
    );
}


/*
 * Writes the presentation cover.
 */
static void write_title_slide(FILE *file) {

     fprintf(file,
        "\\begin{frame}{Project 1}\n"
        "\n"
        "\\centering\n"
        "\n"
        "{\\Large\\textsc{University of Costa Rica}}\\\\[0.15cm]\n"
        "{\\large School of Computer Science and Informatics}\\\\[0.10cm]\n"
        "{\\normalsize CI-0146 Compilers}\\\\[0.35cm]\n"
        "\n"
        "\\rule{0.78\\textwidth}{0.5pt}\\\\[0.22cm]\n"
        "\n"
        "{\\Large\\bfseries Lexical Analyzer}\\\\[0.14cm]\n"
        "{\\normalsize Scanner for the C Programming Language}\\\\[0.22cm]\n"
        "\n"
        "\\rule{0.78\\textwidth}{0.5pt}\\\\[0.38cm]\n"
        "\n"
        "\\begin{columns}[T,onlytextwidth]\n"
        "\n"
        "\\begin{column}{0.46\\textwidth}\n"
        "\\raggedright\n"
        "{\\large\\textbf{Professor:}}\\\\[0.08cm]\n"
        "{\\normalsize Dr. Francisco J. Torres-Rojas}\n"
        "\\end{column}\n"
        "\n"
        "\\begin{column}{0.50\\textwidth}\n"
        "\\raggedleft\n"
        "{\\large\\textbf{Students:}}\\\\[0.08cm]\n"
        "{\\normalsize José Guerra --- C33510}\\\\\n"
        "{\\normalsize Mario Cordero --- C22306}\\\\\n"
        "{\\normalsize Daniel Gómez --- C23310}\n"
        "\\end{column}\n"
        "\n"
        "\\end{columns}\n"
        "\n"
        "\\vfill\n"
        "{\\small II Semester 2026}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes the general process followed by the project.
 */
static void write_process_slide(FILE *file) {

     fprintf(file,
        "\\begin{frame}{General Processing Pipeline}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}[\n"
        "    box/.style={\n"
        "        draw,\n"
        "        rounded corners,\n"
        "        minimum width=2.6cm,\n"
        "        minimum height=0.75cm,\n"
        "        align=center,\n"
        "        font=\\small\n"
        "    }\n"
        "]\n"
        "\n"

        /* Top row */
        "\\node[box] (source) at (-4.8,1.5) "
        "{C Source File};\n"

        "\\node[box] (preprocessor) at (-1.6,1.5) "
        "{Preprocessor};\n"

        "\\node[box] (temporary) at (1.6,1.5) "
        "{Temporary File};\n"

        "\\node[box] (scanner) at (4.8,1.5) "
        "{Lexical Scanner};\n"
        "\n"

        /* Bottom row */
        "\\node[box] (tokens) at (4.8,-1.0) "
        "{Token Collection};\n"

        "\\node[box] (beamer) at (1.6,-1.0) "
        "{Beamer Generator};\n"

        "\\node[box] (latex) at (-1.6,-1.0) "
        "{pdflatex};\n"

        "\\node[box] (pdf) at (-4.8,-1.0) "
        "{PDF Presentation};\n"
        "\n"

        /* Top row arrows */
        "\\draw[->, thick] (source) -- (preprocessor);\n"
        "\\draw[->, thick] (preprocessor) -- (temporary);\n"
        "\\draw[->, thick] (temporary) -- (scanner);\n"
        "\n"

        /* Turn to second row */
        "\\draw[->, thick] (scanner) -- (tokens);\n"
        "\n"

        /* Bottom row arrows */
        "\\draw[->, thick] (tokens) -- (beamer);\n"
        "\\draw[->, thick] (beamer) -- (latex);\n"
        "\\draw[->, thick] (latex) -- (pdf);\n"
        "\n"

        "\\end{tikzpicture}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


static void write_input_source_slide(
    FILE *file,
    const char *source_filename
) {

    fprintf(file,
        "\\begin{frame}{1. Input Source File}\n"
        "\n"
        "The execution begins with the source file received "
        "through the command line.\n"
        "\n"
        "\\vspace{0.35cm}\n"
        "\n"
        "\\begin{block}{Input File}\n"
        "\\texttt{"
    );

    write_latex_escaped(
        file,
        source_filename
    );

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "\\vspace{0.25cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "    \\item This is the original file provided by the user.\n"
        "\n"
        "    \\item It may contain C code, preprocessing directives, "
        "macros, comments, and included files.\n"
        "\n"
        "    \\item The lexical scanner does not process this "
        "file directly.\n"
        "\\end{itemize}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_preprocessing_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{2. Preprocessing}\n"
        "\n"
        "Before lexical analysis, the original source is processed "
        "by the preprocessing stage.\n"
        "\n"
        "\\vspace{0.30cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "\n"
        "    \\item Processes supported "
        "\\texttt{\\#include} directives.\n"
        "\n"
        "    \\item Processes "
        "\\texttt{\\#define} directives.\n"
        "\n"
        "    \\item Recursively expands defined macros.\n"
        "\n"
        "    \\item Removes both forms of C comments.\n"
        "\n"
        "    \\item Reports preprocessing and comment-related "
        "errors whenever they are detected.\n"
        "\n"
        "\\end{itemize}\n"
        "\n"
        "\\vspace{0.25cm}\n"
        "\n"
        "\\begin{block}{Result}\n"
        "The resulting source is written to a dynamically named "
        "temporary file.\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_temporary_file_slide(
    FILE *file,
    const char *source_filename,
    const char *preprocessed_filename
) {

    fprintf(file,
        "\\begin{frame}{3. Temporary Preprocessed File}\n"
        "\n"
        "The preprocessor writes the transformed source to a "
        "dynamically named temporary file.\n"
        "\n"
        "\\vspace{0.25cm}\n"
        "\n"
        "\\begin{block}{Original Source}\n"
        "\\texttt{"
    );

    write_latex_escaped(
        file,
        source_filename
    );

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "\\begin{block}{Scanner Input}\n"
        "\\texttt{"
    );

    write_latex_escaped(
        file,
        preprocessed_filename
    );

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "\\begin{itemize}\n"
        "    \\item The filename is generated dynamically "
        "under the Linux temporary directory.\n"
        "\n"
        "    \\item The program does not delete the file after "
        "the analysis finishes.\n"
        "\n"
        "    \\item Because it resides under \\texttt{/tmp}, "
        "it may later be removed according to the operating "
        "system's temporary-file policy.\n"
        "\n"
        "    \\item This file is the actual input of the "
        "lexical scanner.\n"
        "\\end{itemize}\n"
        "\n"
        "\\begin{block}{Inspection}\n"
        "\\texttt{cat "
    );

    write_latex_escaped(
        file,
        preprocessed_filename
    );

    fprintf(file,
        "}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_scanning_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{4. Lexical Scanning with Flex}\n"
        "\n"
        "The scanner opens the preprocessed file and analyzes "
        "the input one lexeme at a time.\n"
        "\n"
        "\\vspace{0.30cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "\n"
        "    \\item Lexical patterns are defined in "
        "\\texttt{scanner.l} using Flex regular expressions.\n"
        "\n"
        "    \\item Flex generates the scanner implementation "
        "in C.\n"
        "\n"
        "    \\item The program repeatedly invokes "
        "\\texttt{Get\\_Token()}.\n"
        "\n"
        "    \\item Each token stores its type, category, lexeme, "
        "line, and column.\n"
        "\n"
        "    \\item Scanning continues until "
        "\\texttt{TOK\\_EOF} is returned.\n"
        "\n"
        "\\end{itemize}\n"
        "\n"
        "\\begin{block}{Scanner Flow}\n"
        "\\centering\n"
        "\\texttt{Temporary File}\n"
        "$\\rightarrow$\n"
        "\\texttt{Get\\_Token()}\n"
        "$\\rightarrow$\n"
        "\\texttt{Token}\n"
        "$\\rightarrow \\cdots \\rightarrow$\n"
        "\\texttt{TOK\\_EOF}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_token_collection_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{5. Token Collection}\n"
        "\n"
        "Every token returned by the scanner is stored in "
        "memory for later processing.\n"
        "\n"
        "\\vspace{0.30cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "\n"
        "    \\item The token array starts with capacity for "
        "128 elements.\n"
        "\n"
        "    \\item Each recognized token is appended to "
        "the array.\n"
        "\n"
        "    \\item When the array becomes full, its capacity "
        "is doubled using \\texttt{realloc()}.\n"
        "\n"
        "    \\item \\texttt{TOK\\_EOF} stops the scanning loop "
        "but is not stored as presentation data.\n"
        "\n"
        "\\end{itemize}\n"
        "\n"
        "\\begin{block}{Collected Data}\n"
        "\\centering\n"
        "\\texttt{Token[]} + \\texttt{token\\_count}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_beamer_generation_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{6. Beamer Generation}\n"
        "\n"
        "Once scanning is complete, the collected information "
        "is passed to the Beamer generator.\n"
        "\n"
        "\\vspace{0.30cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "\n"
        "    \\item Receives the original source filename.\n"
        "\n"
        "    \\item Receives the preprocessed temporary filename.\n"
        "\n"
        "    \\item Receives the complete token array and "
        "token count.\n"
        "\n"
        "    \\item Calculates lexical-category statistics.\n"
        "\n"
        "    \\item Generates tables, charts, lexical-error "
        "reports, and presentation content.\n"
        "\n"
        "\\end{itemize}\n"
        "\n"
        "\\begin{block}{Generated File}\n"
        "\\centering\n"
        "\\texttt{presentation/presentation.tex}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


static void write_pdf_generation_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{7. PDF Generation and Visualization}\n"
        "\n"
        "After the Beamer source has been generated, the final "
        "presentation is produced automatically.\n"
        "\n"
        "\\vspace{0.35cm}\n"
        "\n"
        "\\begin{itemize}\n"
        "\n"
        "    \\item \\texttt{pdflatex} compiles the generated "
        "LaTeX source into a PDF document.\n"
        "\n"
        "    \\item Compilation output is redirected to "
        "\\texttt{presentation/pdflatex.out} for diagnostics.\n"
        "\n"
        "    \\item If the compilation succeeds, the PDF is "
        "opened automatically with Evince in presentation mode.\n"
        "\n"
        "\\end{itemize}\n"
        "\n"
        "\\begin{block}{Final Output}\n"
        "\\centering\n"
        "\\texttt{presentation/presentation.pdf}\n"
        "\\end{block}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_results_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{Results}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\vfill\n"
        "\n"
        "{\\Huge\\bfseries Scanning Results}\\\\[0.45cm]\n"
        "\n"
        "{\\large\n"
        "Preprocessed source code, lexical statistics, "
        "category distribution, and detected errors\n"
        "}\n"
        "\n"
        "\\vfill\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

static void write_code_legend(FILE *file) {

    fprintf(file,
        "\\vspace{0.15cm}\n"
        "\\centering\n"
        "\\tiny\n"
        "\n"
        "\\colorbox{keywordbg}{"
        "\\textcolor{keywordcolor}{\\textbf{Keyword}}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{identifierbg}{"
        "\\textcolor{identifiercolor}{Identifier}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{constantbg}{"
        "\\textcolor{constantcolor}{\\textbf{Constant}}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{stringbg}{"
        "\\textcolor{stringcolor}{\\textit{String}}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{operatorbg}{"
        "\\textcolor{operatorcolor}{\\textbf{Operator}}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{punctuatorbg}{"
        "\\textcolor{punctuatorcolor}{Punctuator}}"
        "\\hspace{0.12cm}\n"

        "\\colorbox{errorbg}{"
        "\\textcolor{errorcolor}{\\textbf{Error}}}\n"
        "\n"
    );
}

static void write_category_legend_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{Lexical Category Legend}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\vspace{0.3cm}\n"
        "\n"
        "\\begin{tabular}{ll}\n"
        "\\textbf{Category} & "
        "\\textbf{Visual Representation} \\\\ \\hline\n"
        "\n"

        "Keyword & "
        "\\colorbox{keywordbg}{"
        "\\textcolor{keywordcolor}{\\textbf{keyword}}} \\\\[0.18cm]\n"

        "Identifier & "
        "\\colorbox{identifierbg}{"
        "\\textcolor{identifiercolor}{identifier}} \\\\[0.18cm]\n"

        "Constant & "
        "\\colorbox{constantbg}{"
        "\\textcolor{constantcolor}{\\textbf{constant}}} \\\\[0.18cm]\n"

        "String literal & "
        "\\colorbox{stringbg}{"
        "\\textcolor{stringcolor}{\\textit{string}}} \\\\[0.18cm]\n"

        "Operator & "
        "\\colorbox{operatorbg}{"
        "\\textcolor{operatorcolor}{\\textbf{operator}}} \\\\[0.18cm]\n"

        "Punctuator & "
        "\\colorbox{punctuatorbg}{"
        "\\textcolor{punctuatorcolor}{punctuator}} \\\\[0.18cm]\n"

        "Lexical error & "
        "\\colorbox{errorbg}{"
        "\\textcolor{errorcolor}{\\textbf{error}}} \\\\\n"

        "\\end{tabular}\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}

/*
 * Writes a summary table containing the lexical categories
 * found by the scanner.
 */
static void write_statistics_slide(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Lexical Analysis Summary}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tabular}{lr}\n"
        "\\textbf{Category} & "
        "\\textbf{Count} \\\\ \\hline\n"
        "\n"
        "Keywords & %zu \\\\\n"
        "Identifiers & %zu \\\\\n"
        "Constants & %zu \\\\\n"
        "String literals & %zu \\\\\n"
        "Operators & %zu \\\\\n"
        "Punctuators & %zu \\\\\n"
        "Lexical errors & %zu \\\\\n"
        "\\hline\n"
        "\\textbf{Total} & \\textbf{%zu} \\\\\n"
        "\\end{tabular}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count,
        stats->total_tokens
    );
}


/*
 * Writes a histogram containing the number of tokens
 * in each lexical category.
 */
static void write_histogram(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Histogram of Lexical Categories}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}\n"
        "\n"
        "\\begin{axis}[\n"
        "    ybar,\n"
        "    width=11.5cm,\n"
        "    height=6cm,\n"
        "    ylabel={Count},\n"
        "    symbolic x coords={"
        "Keyword,Identifier,Constant,String,"
        "Operator,Punctuator,Error},\n"
        "    xtick=data,\n"
        "    x tick label style={\n"
        "        rotate=35,\n"
        "        anchor=east,\n"
        "        font=\\scriptsize\n"
        "    },\n"
        "    ymin=0,\n"
        "    nodes near coords,\n"
        "    enlargelimits=0.15\n"
        "]\n"
        "\n"
        "\\addplot coordinates {\n"
        "    (Keyword,%zu)\n"
        "    (Identifier,%zu)\n"
        "    (Constant,%zu)\n"
        "    (String,%zu)\n"
        "    (Operator,%zu)\n"
        "    (Punctuator,%zu)\n"
        "    (Error,%zu)\n"
        "};\n"
        "\n"
        "\\end{axis}\n"
        "\n"
        "\\end{tikzpicture}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count
    );
}


/*
 * Writes the lexical-error slide.
 */
static void write_error_slide(
    FILE *file,
    const Token *tokens,
    size_t token_count
) {
    size_t error_count = 0;

    for (size_t i = 0; i < token_count; i++) {

        if (tokens[i].category == CAT_ERROR) {
            error_count++;
        }
    }

    fprintf(file,
        "\\begin{frame}{Lexical Errors}\n"
        "\n"
    );

    if (error_count == 0) {

        fprintf(file,
            "\\begin{block}{Result}\n"
            "No lexical errors were found.\n"
            "\\end{block}\n"
        );

    } else {

        fprintf(file,
            "%zu lexical errors were found.\n"
            "\n"
            "\\vspace{0.3cm}\n"
            "\n"
            "\\begin{tabular}{lll}\n"
            "\\textbf{Lexeme} & "
            "\\textbf{Line} & "
            "\\textbf{Column} \\\\ \\hline\n",
            error_count
        );

        for (size_t i = 0; i < token_count; i++) {

            if (tokens[i].category != CAT_ERROR) {
                continue;
            }

            fprintf(file, "\\texttt{");

            write_latex_escaped(
                file,
                tokens[i].lexeme
            );

            fprintf(file,
                "} & %d & %d \\\\\n",
                tokens[i].line,
                tokens[i].column
            );
        }

        fprintf(file,
            "\\end{tabular}\n"
        );
    }

    fprintf(file,
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Writes one sector of the dynamic pie chart.
 */
static void write_pie_sector(
    FILE *file,
    double start_angle,
    double end_angle,
    const char *color
) {
    if (end_angle <= start_angle) {
        return;
    }

    fprintf(file,
        "\\path[\n"
        "    fill=%s,\n"
        "    draw=white,\n"
        "    thick\n"
        "]\n"
        "(axis cs:%.4f,0) --\n"
        "(axis cs:%.4f,1)\n"
        "plot[\n"
        "    domain=%.4f:%.4f,\n"
        "    samples=30\n"
        "] (axis cs:\\x,1)\n"
        "-- (axis cs:%.4f,0)\n"
        "-- cycle;\n"
        "\n",

        color,
        start_angle,
        start_angle,
        start_angle,
        end_angle,
        end_angle
    );
}


/*
 * Writes a dynamic pie chart based on lexical categories.
 */
static void write_pie_chart(
    FILE *file,
    const BeamerStats *stats
) {

    fprintf(file,
        "\\begin{frame}{Distribution of Lexical Categories}\n"
        "\n"
    );

    if (stats->total_tokens == 0) {

        fprintf(file,
            "\\centering\n"
            "\n"
            "No tokens were found to display.\n"
            "\n"
            "\\end{frame}\n"
            "\n"
        );

        return;
    }

    double angle = 0.0;

    double keyword_angle =
        360.0 *
        (double) stats->keyword_count /
        (double) stats->total_tokens;

    double identifier_angle =
        360.0 *
        (double) stats->identifier_count /
        (double) stats->total_tokens;

    double constant_angle =
        360.0 *
        (double) stats->constant_count /
        (double) stats->total_tokens;

    double string_angle =
        360.0 *
        (double) stats->string_literal_count /
        (double) stats->total_tokens;

    double operator_angle =
        360.0 *
        (double) stats->operator_count /
        (double) stats->total_tokens;

    double punctuator_angle =
        360.0 *
        (double) stats->punctuator_count /
        (double) stats->total_tokens;

    double error_angle =
        360.0 *
        (double) stats->error_count /
        (double) stats->total_tokens;

    fprintf(file,
        "\\centering\n"
        "\n"
        "\\begin{tikzpicture}\n"
        "\n"
        "\\begin{polaraxis}[\n"
        "    hide axis,\n"
        "    xmin=0,\n"
        "    xmax=360,\n"
        "    ymin=0,\n"
        "    ymax=1,\n"
        "    width=7cm,\n"
        "    height=7cm\n"
        "]\n"
        "\n"
    );

    write_pie_sector(
        file,
        angle,
        angle + keyword_angle,
        "blue!65"
    );
    angle += keyword_angle;

    write_pie_sector(
        file,
        angle,
        angle + identifier_angle,
        "green!60"
    );
    angle += identifier_angle;

    write_pie_sector(
        file,
        angle,
        angle + constant_angle,
        "orange!70"
    );
    angle += constant_angle;

    write_pie_sector(
        file,
        angle,
        angle + string_angle,
        "cyan!60"
    );
    angle += string_angle;

    write_pie_sector(
        file,
        angle,
        angle + operator_angle,
        "violet!60"
    );
    angle += operator_angle;

    write_pie_sector(
        file,
        angle,
        angle + punctuator_angle,
        "yellow!70"
    );
    angle += punctuator_angle;

    write_pie_sector(
        file,
        angle,
        angle + error_angle,
        "red!65"
    );

    fprintf(file,
        "\\end{polaraxis}\n"
        "\n"
        "\\end{tikzpicture}\n"
        "\n"
        "\\scriptsize\n"
        "\n"
        "\\begin{tabular}{lll}\n"
        "\\textcolor{blue!65}{\\rule{0.25cm}{0.25cm}} "
        "Keywords: %zu &\n"
        "\\textcolor{green!60}{\\rule{0.25cm}{0.25cm}} "
        "Identifiers: %zu &\n"
        "\\textcolor{orange!70}{\\rule{0.25cm}{0.25cm}} "
        "Constants: %zu \\\\[0.15cm]\n"
        "\n"
        "\\textcolor{cyan!60}{\\rule{0.25cm}{0.25cm}} "
        "Strings: %zu &\n"
        "\\textcolor{violet!60}{\\rule{0.25cm}{0.25cm}} "
        "Operators: %zu &\n"
        "\\textcolor{yellow!70}{\\rule{0.25cm}{0.25cm}} "
        "Punctuators: %zu \\\\[0.15cm]\n"
        "\n"
        "\\textcolor{red!65}{\\rule{0.25cm}{0.25cm}} "
        "Errors: %zu & &\n"
        "\\end{tabular}\n"
        "\n"
        "\\end{frame}\n"
        "\n",

        stats->keyword_count,
        stats->identifier_count,
        stats->constant_count,
        stats->string_literal_count,
        stats->operator_count,
        stats->punctuator_count,
        stats->error_count
    );
}


/*
 * Writes the final presentation slide.
 */
static void write_end_slide(FILE *file) {

    fprintf(file,
        "\\begin{frame}{End}\n"
        "\n"
        "\\centering\n"
        "\n"
        "\\vfill\n"
        "\n"
        "{\\Huge\\bfseries Thank You}\\\\[0.45cm]\n"
        "{\\Large Project 1 --- Lexical Analyzer}\\\\[0.20cm]\n"
        "{\\large Scanner for the C Programming Language}\n"
        "\n"
        "\\vfill\n"
        "\n"
        "\\end{frame}\n"
        "\n"
    );
}


/*
 * Generates the complete Beamer .tex file.
 */
int beamer_generate(
    const char *output_filename,
    const char *source_filename,
    const char *preprocessed_filename,
    const Token *tokens,
    size_t token_count
) {

    if (output_filename == NULL ||
        source_filename == NULL ||
        preprocessed_filename == NULL) {

        return 0;
    }

    if (tokens == NULL && token_count > 0) {
        return 0;
    }

    FILE *file = fopen(output_filename, "w");

    if (file == NULL) {

        fprintf(
            stderr,
            "Error: no se pudo crear %s\n",
            output_filename
        );

        return 0;
    }

    BeamerStats stats;

    calculate_stats(
        tokens,
        token_count,
        &stats
    );

    write_preamble(file);

    fprintf(file, "\\begin{document}\n\n");

    write_title_slide(file);

    write_process_slide(file);

    write_input_source_slide(
        file,
        source_filename
    );

    write_preprocessing_slide(file);

    write_temporary_file_slide(
        file,
        source_filename,
        preprocessed_filename
    );

    write_scanning_slide(file);

    write_token_collection_slide(file);

    write_beamer_generation_slide(file);

    write_pdf_generation_slide(file);

    write_results_slide(file);

    write_category_legend_slide(file);
    
    if (!write_source_slides(
            file,
            preprocessed_filename,
            tokens,
            token_count)) {

        fclose(file);

        return 0;
    }

    write_statistics_slide(
        file,
        &stats
    );

    write_histogram(
        file,
        &stats
    );

    write_pie_chart(
        file,
        &stats
    );

    write_error_slide(
        file,
        tokens,
        token_count
    );

    write_end_slide(file);

    fprintf(file, "\\end{document}\n");

    fclose(file);

    return 1;
}