#ifndef BEAMER_GENERATOR_H
#define BEAMER_GENERATOR_H

#include <stddef.h>
#include "token.h"

/*
 * Generates a Beamer presentation using the tokens
 * produced by the scanner.
 *
 * output_filename:
 *     Path where the generated .tex file will be stored.
 *
 * source_filename:
 *     Original source file received by the program.
 *
 * preprocessed_filename:
 *     Temporary file generated by the preprocessor.
 *
 * tokens:
 *     Array of tokens produced by the scanner.
 *
 * token_count:
 *     Number of tokens contained in the array.
 *
 * Returns:
 *     1 on success.
 *     0 on error.
 */
int beamer_generate(
    const char *output_filename,
    const char *source_filename,
    const char *preprocessed_filename,
    const Token *tokens,
    size_t token_count
);

#endif